### PR TITLE
Use argparse

### PR DESCRIPTION
**Pull request by palaviv**
This PR changes the argument parsing to work with python argparse library.

### CODE REVIEW

**Comment by Pat-Carter** [comment]
That is a lot of changes  :-(

I'll have a look through them in detail - but I'll be honest, I'm not a great fan of replacing named arguments in functions with a single generic "args".

e.g. 

def play(filename, transcode=False, transcoder=None, transcode_options=None, transcode_bufsize=0, device_name=None, server_port=None):

vs 

def play(args):

I don't want to be overly critical. You're probably right,  argparse probably is a better solution than manually parsing the arguments, but it really is a matter of personal taste & I will have to continue maintaining this in future.

**Comment by palaviv** [comment]
How about now? I changed the function's back to take named arguments.
I do think it is more clear and easier to maintain using argparse.

**Comment by Pat-Carter** [comment]
I'm sorry, but I won't be merging this change.

It includes a LOT of code changes and doesn't fix any bugs or add any new features.

The number of changes increases the likelihood of introducing new bugs and checking it will create unnecessary work for me. 

The usage of argparse is essentially a matter of preference. Yes, the existing argument parsing is a little clumsy but works and is very well tested. As I said before, I'm the one that has to support this code in the future.

I am more interested in the subtitle functionality in your other pull request as that does add a new feature but I'm afraid that will have to be done under the current coding style, at least for the time being.

**Comment by palaviv** [comment]
As this is your project it is your prerogative to decline this PR but please let me argue in the benefits of moving to argparse:

1. This is the pythonic way.
2. This PR actually reduces the line of code.
3. You are using argparse a library that is in the stdlib of python and millions of people use every day. The probability for bugs in argparse is less likely then in a code of your own.
4. You receive all the features argparse has to offer.
5. Most python programmers know argparse well and will have an easier time contributing to your project (The reason this PR was opened :) ).
6.  I think that the current argument parsing code is complicated and will get more so as more options are added. argparse gives you hierearchy using the subparser and groups.

> The number of changes increases the likelihood of introducing new bugs and checking it will create unnecessary work for me.

As this change only the argument parsing without touching the implementation, the amount of checking needed to be done is very minimal.

**Comment by Pat-Carter** [comment]
I take your point, and to some extent I do agree with your points.

However, please also try to understand my position.

I initially wrote this script some years ago, purely as a means to send video files to my Chromecast. 
It does that. It was not an exercise in writing beautiful code. I have been writing software professionally for over 30 years and this was just a means of getting the job done. I don't feel like I have anything to prove.

I'm happy to share the code and delighted if people find it useful. I do not get paid to maintain it. Though I am happy to help people if they are having problems getting it to work or if they want an additional feature.

This project attracted a surprising amount of interest just a few months ago and suddenly there was a lot of advice and suggestions appearing from a lot of different people. I've taken some of them on board and rejected some of them. It has meant that I have had to divert my attention from other things that I was doing.

Thanks you for your interest and your advice. I'm glad that you have found this project useful.

Please don't feel bad that I've decided not to take this change. It isn't intended as any kind of judgement on the quality of your code - it is just that it isn't the way I want to go with this project at this stage.

**Pull request closed without merging**
