### PR TITLE
Compatibility with Windows

### PR DESCRIPTION
**Pull request by polaris-**
* Use tempfile.gettempdir() to get the temp directory for the pid file instead of hardcoding /tmp/.
* Always add a / between the port number and the file path in the content URL. The / always gets removed on line 118 in do_GET. This fixes the URL on Windows and should not have any noticeable effect on Linux.
* In write_response, add the binary flag when opening the video file. Shouldn't have any effect on Linux but fixes an issue with Windows.

I tested with a few videos on Windows but I couldn't get the program to work within my Ubuntu VM so I can't test there. The changes I made should all be pretty safe so I don't think Linux would've broken as a result.

### CODE REVIEW

**Comment by polaris-** [comment]
Also should note, the following requirement programs were tested and working for me:
* ffmpeg win32/64 build (Tested: https://ffmpeg.zeranoe.com/builds/)
* file win32 build (Tested: https://github.com/alberthdev/file-win32/releases)

I did not test but if you had a build of avconv then that should work too.

**Comment by Pat-Carter** [comment]
I've had a look and I'm not sure about that additional "/" in the URL.

It shows up as a double "//" for me in the script output.
`
192.168.1.10 - - [03/Aug/2016 17:13:22] "GET //home/pat/Tourists+-+So+Good+To+Be+Back+Home.mp4 HTTP/1.1" 200 -`

What sort of problem was this causing in Windows?

**Comment by polaris-** [comment]
@Pat-Carter 
With the way it was before, it would send a URL like this on Windows due to the difference in file paths:
`URL & content-type:  http://10.0.0.2:58586H%3A%5C%5CBalloons.mkv video/mp4`

Since that's not a valid URL, the Chromecast chokes and doesn't even attempt to get the file.

**Comment by polaris-** [comment]
@Pat-Carter 
So does silently closing this PR mean that the file path issue won't be fixed?

**Comment by rfigueroa** [comment]
is this issue going to be fixed in a different manner?

**Comment by Pat-Carter** [comment]
I don't want to start adding code changes for other platforms beyond Linux.

As I don't have access to a windows machine, I can't realistically support windows compatibility.

I plan to add other features in the future which would be problematic on windows. For example, a curses GUI - or perhaps GTK.

So, thank you for taking an interest, but I will not be merging this change.

**Comment by polaris-** [comment]
@Pat-Carter
This isn't really so much about supporting platforms beyond Linux. It's an issue with lazy code that just happens to work on Linux.

If the double /s really bothers you that much then it's as simple as changing
`"http://%s:%s/%s" % (webserver_ip, str(server.server_port), urllib.quote_plus(filename, "/"))`
to
`"http://%s:%s/%s" % (webserver_ip, str(server.server_port), urllib.quote_plus(filename))`
and suddenly everything would work perfectly on Linux or Windows (and most likely OS X, which I assume works anyway) with minimum changes.

If you design the next iterations properly (separating the GUI and code that does the actual work) then there really shouldn't be much of an issue, even if you don't intend on making a GTK or curses GUI work on Windows. 

Why bother even cherry picking the other changes I made when there was technically nothing wrong with them from a Linux standpoint? I respect that it's your project and you can do what you want, but this argument in defense of not fixing buggy code just feels really silly and doesn't make sense to me.

**Pull request closed without merging**
