### PR TITLE
Add options to print status and set volume

### PR DESCRIPTION
**Pull request by dohliam**
I added a few useful options that are available in PyChromecast but weren't yet included in stream2chromecast. I have found it really useful to be able to control the volume when streaming to Chromecast.

Having direct access to the Chromecast status opens up a wide range of possibilities for scripting interaction with the device. For example, I've used stream2chromecast as the base for my [Chromecast playlist script](https://github.com/dohliam/cast-playlist), and being able to query the status gives access to all sorts of useful information -- the current playing video, the current volume, whether the device is active or muted etc.

There are a few other nice features supported by PyChromecast, such as playing YouTube videos and seeking to a particular point in a video. I'll try to add those eventually too, once I've figured them out.

### CODE REVIEW

**Comment by Pat-Carter** [comment]
Wow - thanks again! 

:-)

Pausing seems to be a problem when transcoding from an unsupported format. I guess seeking might be tricky there as well.

**Comment by Pat-Carter** [comment]
I don't know if this affects Cast-Playlist, but I've just added an enqueue parameter.
Someone asked me for this a few weeks ago but I hadn't got around to committing it.

The problem was that the Chromecast caches a minute or so of video - so the stream2chromecast script completes about a minute before the end of the media file.

So if there was a script that chained together multiple videos, it would kill the player app early before the end of the each file and start playing the next one.

The enqueue parameter just waits for the Chromecast player to go into Idle status before playing the file - which should mean any previous file has completed.

I hope this hasn't caused you any problems. 

cheers,

Pat

**Comment by dohliam** [comment]
Hey, that's great! Thanks for adding this feature. The queuing issue you described is exactly how cast-playlist got started -- I was looking for a way to play multiple videos and just using something like `stream2chromecast *.mp4` would always jump to the next video after about a minute or so, which was pretty frustrating.

I actually have a whole sleep routine in the script to handle this right now, where it calculates the total length of the video in advance, then starts a timer and plays the video, and then when it thinks the video is over it just goes to sleep for the remaining amount of time (plus about 15 seconds or so to allow for the time the Chromecast takes to start playing the new video).

Now that there's an enqueue parameter it sounds like this issue may be resolved and I can skip the hacky sleep workaround when playing multiple videos. :smile:

I'll test it out later today and update cast-playlist to incorporate this new feature.

**Comment by dohliam** [comment]
The new enqueue parameter works perfectly! I've updated cast-playlist to remove the old kludgy way of doing this. Thanks again :+1:

**Comment by Pat-Carter** [comment]
That's great- I'm glad it worked. 
:-)

**Pull request merged**
