### PR TITLE
Misc. additions for playing from a URL

### PR DESCRIPTION
**Pull request by FrobozzElectric**
Adding in a few things to make podcast listening easier.

### CODE REVIEW

**Comment by Pat-Carter** [comment]
Hi,

Thanks for taking an interest. 

Some comments... 


1. 302 is a valid response code too 

You're partially right there, but, if the response is a redirection, i.e.  a 301, 302 or 303, we haven't got the data we need unless we actually follow the redirection.

The point of that function is to retrieve the Content-Type header value that goes with the media file at the URL. So we send a HEAD request to the URL to get the HTTP header values.

If the request returns a 200, it should return a Content-type header field (e.g. "Content-type:video/mp4".) We need the content-type to send the URL and the content type to the Chromecast and tell it to play from the URL.

If the response from the server is a redirection, that would include a Location header (i.e. the URL to redirect to). We would then have to run the same HEAD request on that Location to get the Content-type.

Also, there is no reason why the redirected location should not also return a redirection. So it would have to be in a loop, with a maximum level value of say 10 to prevent redirect loops.

Ultimately we do need to get to a URL that returns a status 200.

What happens with your change is that it gets the 302 and finds that there is no Content-type header. It then defaults to "video/mp4" and hopes the Chromecast will cope with that.



2. Auto URL detection 

The playurl option was not really intended to be used for anything except troubleshooting.

I added it to help someone diagnose some connectivity issues but it was never meant to be part of the functionality of Stream2chromecast. This script was really intended to stream media from the user's PC rather than off of the web.

The playurl option just tells the Chromecast to play the file at a given URL, rather than streaming it from the PC. The data never actually goes through the PC.

I prefer to keep playurl as a separate option. It is pretty much a deprecated function and I'm hoping to be able to remove it at some point in the future. It doesn't work on a large number or URLs because the a lot of files on the web are in the wrong format, or not downloadable, or not fragmented. 

There's really no need to use it anyway. The -transcode option will accept a URL and work in many more cases than -playurl. The -transcode option can now also play streaming URLs such as radio stations etc.



3. Ability to start from a point in a URL 

I think this will only work with a few web based URLs and won't work when streaming from the PC.

The built-in webserver in Stream2Chromcast just serves up the local file. It doesn't know how many bytes per minute the file is. We would have to work out whereabouts in the file e.g. 25 minutes is.

The transcoder can do this though:-

stream2chromecast.py -transcodeinputopts '-ss 00:15:00' -transcode myfile.mp4

...to start the file at 15 minutes into the file.



If you want to do the 302 work in point 1 - i.e. follow the redirections until it returns a status 200 (up to say a maximum of 10 redirections) I'll be happy to pull that part in.


cheers,

Pat

**Comment by FrobozzElectric** [comment]
Ah, I didn't realize you we planning to deprecate the -playurl option (nor did I realize -transcode could handle URLs or that it was so robust in general). 

Maybe the documentation could be updated to show how to use the -transcode options with URLs?

Also, I understand the concern about redirect loops, so I've made changes to playurl to account for that.

**Comment by Pat-Carter** [comment]
Hi,

Yes, sorry - I thought I had updated the documentation. I'll update that and make it clearer.

To be honest, I didn't think this would really be used for streaming media from the web. I never use it for that. I only added that option to help someone troubleshoot an issue. 

Just a few points on this last change. 

1. 301 & 302 are covered. Maybe we should add 303 (and probably 307 and 308) as well, just for completeness.

2. From a visual check of the new code, it looks like it only checks for a 200 status initially. If it isn't 200 but is 301 or 302 it then loops until it gets any status other than a 301, 302. So, a 301 redirecting to a url that returns a 404 would be considered to be found.

3. A minor point, but could we print out the redirections as they happen URLs - e.g. "redirecting to..." etc.

4. I believe the Location header can contain either an absolute or a relative URL now. So we should probably handle relative URLs as well. https://en.wikipedia.org/wiki/HTTP_location

Also, do you have an example URL that I could use to test this with, please?

cheers,

Pat

**Comment by FrobozzElectric** [comment]
1. I've added in 303, 307 and 308. As long as they all return and absolute "Location:" header, they should work fine.

2. I've added some code in to make sure we end up with a 200.

3. This is a great idea. Added that in too.

4. I haven't added this in yet, mostly because I can't find a good way to test it. Pretty much everywhere returns an absolute path, but I'll play around with nginx configs to see if I can get a URL to test.

Test URLs:

Redirection to a valid .mp3: http://tinyurl.com/j3w8xkl
Redirection to a 404: http://tinyurl.com/hbk3ldz
Infinite redirect loop: https://charlatan.io/loop

Thanks again for looking over this.

**Comment by Pat-Carter** [comment]
Have a look at this gist - it sets up a webserver on localhost and  simulates various absolute and relative redirects to a file using 302s.

https://gist.github.com/Pat-Carter/348248499d747c13fdf07649c710079e

The file itself is returned from http://localhost:8888/one/two/200_file.mp4

The URL /302_absolute returns an absolute redirect to http://localhost:8888/one/two/200_file.mp4
The URL /302_relative_1 returns a relative redirect to /one/two/200_file.mp4
The URL /one/302_relative_2 returns a relative redirect to two/200_file.mp4
The URL /one/two/302_relative_3 returns a relative redirect to 200_file.mp4

**Comment by FrobozzElectric** [comment]
That was super helpful!

The last commit should be able to cover the various kinds of relative paths outlined in the gist.

**Comment by Pat-Carter** [comment]
Thanks & much appreciated - that's merged now.

cheers,

Pat

**Pull request merged**
