### PR TITLE
Add subtitles support

### PR DESCRIPTION
**Pull request by palaviv**
This PR add subtitles support. Currently support only WebVTT format.

### CODE REVIEW

**Comment by Pat-Carter** [comment]
Thanks. Just a few issues though...

1. 
I notice the webserver port for subtitles is hardcoded to 8112.

Originally, the webserver port was just selected as a random free port, but there were some issues raised by people who needed to be able to specify the port number. e.g. because they were behind firewalls etc.

So I added the -port option which overrides the random port selection.

The subtitles server should really follow the same principle.

2.
The  "URL & Content-type" message line - I think that only gets executed if subtitles are specified.

3.
Is it hardcoded to only show English subtitles?

**Comment by palaviv** [comment]
Sorry for the late response.
As for 1,3 I do want to make them configurable but I had some difficulty with the current argument parsing method so I opened PR #22.
As for point 2 I will fix this.

**Comment by palaviv** [comment]
I fixed the point's you have raised.

**Comment by Pat-Carter** [comment]
OK thanks. I'll take a look in the week.

**Comment by Pat-Carter** [comment]
OK - that looks pretty good. 

I've had a play with it and there are just a few points.


1. Could we validate that the subtitle file exists, please. 

If it doesn't exist, just show an info message and continue rather than letting it show a traceback. 
It's not something that bothers me personally but other people will raise an issue about it.



2. The SubRequestHandler class isn't needed.

The existing RequestHandler class serves up a file and has a content-type attribute which is set in the play function. 

i.e. this should work:-

        subtitle_req_handler = RequestHandler
        subtitle_req_handler.content_type = 'text/vtt;charset=utf-8'
        
        sub_server = BaseHTTPServer.HTTPServer((webserver_ip, sub_port), subtitle_req_handler)


The RequestHandler class overrides some of the functions in BaseHTTPRequestHandler that show unnecessary tracebacks on socket errors. See issue #13

Also, it serves the files using Transfer-Encoding:chunked - which I think is needed by some non-Chromecast devices, at least for media files.
I don't know if that applies to subtitle files as well - I only have a Chromecast so I can't test that - but we might as well serve all the files with the same handler if possible.
 
 

3. Usage text
It's not a big deal but in the usage-text example says French subtitles are "en-US", could we tweak that, please.



4. Transcoding & Subtitles
Don't worry too much about this one, but I couldn't get the subtitles to work with the transcode option and I couldn't see why. I'll accept the change without that but I'd love to know why it doesn't work. 

The Chromecast requests the subtitle file and it gets served up OK - but they don't show up on the screen. At that point, I can't see what the difference is. 


thanks,

Pat

**Comment by palaviv** [comment]
Fixed

**Comment by Pat-Carter** [comment]
Sorry, I made a mistake in those comments yesterday.

I think we do need a separate SubRequestHandler class. The content_type value is a class attribute at that stage, not an instance value.

It should work if the SubRequestHandler subclasses RequestHandler and just overrides the content_type. It shouldn't need a do_GET as that is all handled by RequestHandler (along with the chunked transfer-encoding and the handling of socket errors).

So I think the following should be sufficient for SubRequestHandler:-

    class SubRequestHandler(RequestHandler):
        content_type = "text/vtt;charset=utf-8"

**Comment by palaviv** [comment]
Done

**Comment by Pat-Carter** [comment]
Thanks - that's done.

**Comment by jegue** [comment]
that is awesome! but I have one question!  can I change the subtitle colors?

**Pull request merged**
